letsencrypt:
  build: .
  container_name: letsencrypt
  ports:
    - "8089:80"
  volumes:
    - ../certs:/certs
  restart: always
  environment:
    - DOMAINS=ninja.deals
    - EMAIL=contact@ninja.deals
