letsencrypt:
  build: .
  container_name: letsencrypt
  expose:
    - "8089:80"
  volumes:
    - ~/docker-registry/certs:/certs
  restart: always
  environment:
    - DOMAINS=ninja.deals
    - EMAIL=contact@ninja.deals
